version: '3'
services:
    db-data:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: data
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password

    db-web:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: web
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password

    web-service:
        depends_on:
            - db-web
        build: ./web-service
        ports:
            - "5000:5000"
        environment:
            DB_HOST: db:3306
            DB_USER: db_user
            DB_NAME: web
            DB_PASSWORD: db_password

    data-service:
        depends_on:
            - db-data
        build: ./data-service
        ports:
            - "5050:5000"
        environment:
            DB_HOST: db:3306
            DB_USER: db_user
            DB_NAME: data
            DB_PASSWORD: db_password

    ui:
        build: ./ui
        ports:
            - "7777:80"

volumes:
    db_data: {}
